############################################################
# Site settings
############################################################
title                   : "OCMP Docs"
enable_ocmp_development : true

gtm :
  enable                : false
  production            : ""
  development           : "GTM-TBBZ5N4"
############################################################
# Where things are
############################################################
source              : .
destination         : ../.dev/docs
collections_dir     : collections
plugins_dir         : _plugins       # takes an array of strings and loads plugins in that order
layouts_dir         : _layouts
includes_dir        : _includes
data_dir            : _data
sass:
  sass_dir          : _sass
  # style             : compressed
collections:
  posts:
    output          : true
    # permalink       : /post/:slug

############################################################
# Handling Reading
############################################################
safe                : false
include             : 
  - ".htaccess"
exclude             : 
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
keep_files          : [".git", ".svn"]
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false

############################################################
# Filtering Content
############################################################
# Filtering Content
show_drafts         : null #false
limit_posts         : 0
future              : false
unpublished         : false

############################################################
# Serving
############################################################
detach              : false
port                : 4001
host                : 127.0.0.1
baseurl             : "/ocmp"                                    # does not include hostname
show_dir_listing    : false
disable_disk_cache  : true

############################################################
# Conversion
############################################################
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false

############################################################
# Outputting
############################################################
permalink           : date        #pretty
paginate_path       : /page:num
timezone            : null       # 'null'
quiet               : false
verbose             : false
defaults            : []
liquid:
  error_mode        : warn
  strict_filters    : false
  strict_variables  : false

############################################################
# Markdown Processors
############################################################
kramdown:
  auto_ids          : false
  entity_output     : as_char
  toc_levels        : [1, 2, 3, 4, 5, 6]      # '1..6'
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false

############################################################
# Plugins
############################################################
gems              : 
#   - jekyll-tidy
whitelist         : []
plugins           : ['jekyll-seo-tag', 'jekyll-remote-theme']

############################################################
# Front Matter Defaults
############################################################
defaults:
  -
    scope:
      path         : "pages/**"                                    # an empty string here means all files in the project
      type         : "pages"
    values:
      layout       : "default"
      title        : "NOTITLE"
############################################################
################### END OF BASE CONFIG #####################
############################################################

remote_theme: just-the-docs/just-the-docs

# Set a path/url to a logo that will be displayed instead of the title
# logo: "/assets/images/just-the-docs.png"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: false

# search:
#   # Split pages into sections that can be searched individually
#   # Supports 1 - 6, default: 2
#   heading_level: 2
#   # Maximum amount of previews per search result
#   # Default: 3
#   previews: 3
#   # Maximum amount of words to display before a matched word in the preview
#   # Default: 5
#   preview_words_before: 5
#   # Maximum amount of words to display after a matched word in the preview
#   # Default: 10
#   preview_words_after: 10
#   # Set the search token separator
#   # Default: /[\s\-/]+/
#   # Example: enable support for hyphenated search words
#   tokenizer_separator: /[\s/]+/
#   # Display the relative url in search results
#   # Supports true (default) or false
#   rel_url: true
#   # Enable or disable the search button that appears in the bottom right corner of every page
#   # Supports true or false (default)
#   button: false

# Aux links for the upper right navigation
aux_links:
  "OCMP on GitHub":
    - "https://github.com/ChrisMavrommatis/ocmp"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust
# markup / liquid-based content.
# footer_content: "Copyright &copy; 2017-2020 Patrick Marsceill. Distributed by an <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/ChrisMavrommatis/ocmp" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_source: "docs" # the source that your files originate from
gh_edit_view_mode: "blob" # "tree" or "edit" if you want the user to jump into the editor immediately

# Color scheme supports "light" (default) and "dark"
color_scheme: light

#----------------------------------------------------------#
#----------------------------------------------------------#
